# Generated by Django 5.0.4 on 2024-04-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="CustomUser",),
    ]
