# Generated by Django 5.0.4 on 2024-04-27 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("order", "0002_alter_order_cartitem"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="cartItem",),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="cart.cart"
            ),
            preserve_default=False,
        ),
    ]
