# Generated by Django 5.0.4 on 2024-04-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="product_images/placeholder_product.webp",
                upload_to="product_images/",
            ),
        ),
    ]
